server:
  port: 8086

spring:
  application:
    name: fraud-service

  datasource:
    # PIVOT 1: Changed 'localhost' to the internal container name 'fraud-db'
    url: jdbc:postgresql://fraud-db:5432/fraud_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      # PIVOT 2: Changed to internal broker listener
      bootstrap-servers: kafka:9092
      group-id: fraud-detection-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # PIVOT 3: Changed to internal broker listener
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    enabled: false