server:
  port: 8083

spring:
  application:
    name: ledger-service

  datasource:
    # PIVOT 1: Changed 'localhost' to the internal container name 'ledger-db'
    url: jdbc:postgresql://ledger-db:5432/ledger_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    # PIVOT 2: Changed from localhost:9094 to the internal container broker listener
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ledger-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    com.logicminers.banking: INFO