package com.logicminers.banking.auth.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

@Entity
@Table(
        name = "users",
        indexes = {
                @Index(name = "idx_username", columnList = "username"),
                @Index(name = "idx_email", columnList = "email")
        }
)
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Builder
public class User implements UserDetails { // 🛑 THE FIX: Conforms to Spring Security's contract

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Version
    private Long version;

    @Column(nullable = false, unique = true, length = 50)
    private String username;

    @Column(nullable = false, unique = true, length = 100)
    private String email;

    @Column(nullable = false)
    private String password;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role;

    @Builder.Default
    @Column(nullable = false)
    private boolean enabled = false;

    @Builder.Default
    @Column(nullable = false)
    private boolean accountNonLocked = true;

    @Builder.Default
    @Column(nullable = false)
    private int failedLoginAttempts = 0;

    private LocalDateTime accountLockedAt;
    private String emailVerificationToken;
    private LocalDateTime emailVerificationExpiry;
    private String passwordResetToken;
    private LocalDateTime passwordResetExpiry;
    private LocalDateTime lastLoginAt;

    @Builder.Default
    @Column(nullable = false)
    private boolean deleted = false;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    // ==========================
    // DOMAIN METHODS
    // ==========================

    public void recordSuccessfulLogin(){
        this.failedLoginAttempts = 0;
        this.accountNonLocked = true;
        this.lastLoginAt = LocalDateTime.now();
    }

    public void recordFailedLogin(){
        this.failedLoginAttempts++;
        if(this.failedLoginAttempts >= 5){
            this.accountNonLocked = false;
            this.accountLockedAt = LocalDateTime.now();
        }
    }

    public void enableAccount(){
        this.enabled = true;
        this.emailVerificationToken = null;
        this.emailVerificationExpiry = null;
    }

    public void changePassword(String hashedPassword){
        this.password = hashedPassword;
        this.passwordResetToken = null;
        this.passwordResetExpiry = null;
    }

    public void lockAccount(){
        this.accountNonLocked = false;
        this.accountLockedAt = LocalDateTime.now();
    }

    public void unlockAccount(){
        this.accountNonLocked = true;
        this.failedLoginAttempts = 0;
        this.accountLockedAt = null;
    }

    public void updateEmailVerificationToken(String token, LocalDateTime expiry){
        this.emailVerificationToken = token;
        this.emailVerificationExpiry = expiry;
    }

    public void updatePasswordResetToken(String token, LocalDateTime expiry){
        this.passwordResetToken = token;
        this.passwordResetExpiry = expiry;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    // ==========================
    // SPRING SECURITY USERDETAILS
    // ==========================

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        // Translates your custom Role into a format Spring Security understands
        return List.of(new SimpleGrantedAuthority("ROLE_" + this.role.name()));
    }

    // getPassword() and getUsername() are automatically generated by Lombok's @Getter!

    @Override
    public boolean isAccountNonExpired() {
        // Logic Miners business logic: accounts don't currently expire
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        // Wired directly to your database field
        return this.accountNonLocked;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        // Logic Miners business logic: passwords don't currently expire
        return true;
    }

    @Override
    public boolean isEnabled() {
        // Wired to your email verification and soft-delete logic
        return this.enabled && !this.deleted;
    }
}