apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: banking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ibrar09/auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://auth-db:5432/auth_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: banking-system
spec:
  ports:
    - port: 8081
  selector:
    app: auth-service