apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  namespace: banking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: ibrar09/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            # 🟢 Disabling Redis to prevent connection crashes
            - name: spring.data.redis.repositories.enabled
              value: "false"
            - name: spring.cloud.gateway.redis-rate-limiter.enabled
              value: "false"
            - name: management.health.redis.enabled
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: banking-system
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090