apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-deployment
  namespace: banking-system
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: ibrar09/transaction-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.banking-system.svc.cluster.local:9092"
            # NEW: Telling the app exactly where the K8s database is!
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://transaction-db-service.banking-system.svc.cluster.local:5432/transaction_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking-system
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082