server:
  port: 8084

spring:
  application:
    name: beneficiary-service

  datasource:
    # PIVOT: Changed 'localhost' to the docker container name 'beneficiary-db'
    url: jdbc:postgresql://beneficiary-db:5432/beneficiary_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    enabled: false